# Use the official Python base image
FROM python:latest

# WORKDIR /backend

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Expose the port that the Flask app will run on
EXPOSE 5000

# Start the Flask application
CMD ["flask", "run"]
