name: Frontend Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up node
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: |
        cd frontend
        npm install
    - name: Run svelte check and linting
      run: |
        cd frontend
        npm run check
        npm run lint
    # - name: Test with pytest
    #   run: |
    #     cd frontend

